paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Todos los productos se obtuvieron correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        "500":
          description: Error interno del servidor
    post:
      summary: Crea un nuevo producto
      tags:
        - Productos
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Products"
  /api/products/manageProducts/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Todos los productos se obtuvieron correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        "500":
          description: Error interno del servidor
  /api/products/{pid}:
    get:
      summary: Obtiene un producto por su id
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          description: Id del producto
          required: true
          schema:
            type: string
      responses:
        "200":
          description: El producto se obtuvo correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: El producto no existe
        "500":
          description: Error interno del servidor
  /api/products/update/{pid}:
    put:
      summary: Actualiza un producto por su id
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          description: Id del producto
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: El producto se actualizó correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: El producto no existe
        "500":
          description: Error interno del servidor
  /api/products/delete/{pid}:
    delete:
      summary: Elimina un producto por su id
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          description: Id del producto
          required: true
          schema:
            type: string
      responses:
        "200":
          description: El producto se eliminó correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: El producto no existe
        "500":
          description: Error interno del servidor
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: id del producto autogenerado por mongo
        name:
          type: string
          description: nombre del producto
        description:
          type: string
          description: descripción del producto
        price:
          type: number
          description: precio del producto
        code:
          type: string
          description: código del producto, debe ser único
        category:
          type: string
          description: categoría del producto
        stock:
          type: number
          description: stock del producto
        thumbnail:
          type: string
          description: url de la imagen del producto
        owner:
          type: string
          description: id del usuario que creó el producto
      example:
        _id: 60b9b8b9e6b3c3b4b8c9b8b9
        name: "Producto 1"
        description: "Descripción del producto 1"
        price: 100
        code: "0001"
        category: "category 1"
        stock: 10
        thumbnail: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.freepik.es%2Ffotos-vectores-gratis%2"
    Products:
      type: array
      items:
        $ref: "#/components/schemas/Product"
  requestBodies:
    updateProduct:
      type: object
      properties:
        name:
          type: string
          description: nombre del producto
        description:
          type: string
          description: descripción del producto
        price:
          type: number
          description: precio del producto
        code:
          type: string
          description: código del producto, debe ser único
        category:
          type: string
          description: categoría del producto
        stock:
          type: number
          description: stock del producto
        thumbnail:
          type: string
          description: url de la imagen del producto
        owner:
          type: string
          description: id del usuario que creó el producto
      example:
        name: "Producto 1"
        description: "Descripción del producto 1"
        price: 100
        code: "0001"
        category: "category 1"
        stock: 10
        thumbnail: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.freepik.es%2Ffotos-vectores-gratis%2"
